version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - node -v
        - npm run-script build
  artifacts:
    baseDirectory: marketAnon
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*